package pl.krgr.chinczyk.network;

public interface Notifications {
	public String NOTIFICATION_PREFIX 		= "NOTIFICATION: ";
	public String SERVER_STOP				= NOTIFICATION_PREFIX + "SERVER_STOP ";
	public String NEW_ROOM_INFO				= NOTIFICATION_PREFIX + Responses.ROOM_INFO;
	public String ROOM_CHANGED				= NOTIFICATION_PREFIX + "CHANGED " + Responses.ROOM_INFO;
	public String GAME_RESULT				= NOTIFICATION_PREFIX + "GAME RESULT MESSAGE: %s";
	public String GAME_QUERY				= NOTIFICATION_PREFIX + "GAME QUERY MESSAGE: %s";
	public String GAME_ERROR				= NOTIFICATION_PREFIX + "GAME ERROR MESSAGE: %s";
	public String GAME_STARTED				= NOTIFICATION_PREFIX + "GAME STARTED NOTIFICATION";
	public String REQUEST_ROLL				= NOTIFICATION_PREFIX + "REQUEST_ROLL";
	public String REQUEST_MOVE				= NOTIFICATION_PREFIX + "REQUEST MOVE, CAMP: %s, MOVEMENT: %d";
	public String MOVE						= NOTIFICATION_PREFIX + "CAMP: %s, PAWN POSITION: %d, MOVEMENT: %d";
	public String CLEAR_KILLS				= NOTIFICATION_PREFIX + "CLEAR KILLS, CAMP: %s";
	public String END_GAME					= NOTIFICATION_PREFIX + "END GAME, PLACES: %s";
}
